# Conexão com PostgreSQL (Aiven)
spring.datasource.url=jdbc:postgresql://bibliotecanoite-bibliotecafuctura.f.aivencloud.com:20187/defaultdb?sslmode=require
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_vyBJEJ7BcvgbEy8RKLt
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
